# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99e0c51b595fc89f856381280b8ae3b128faab9c6d1524765f4c93caa78e8748010eb8012f18d2b3477002b15c0f09d374f8eb7def922f87ffb57b5dff9caf2c

test:
  secret_key_base: 2ad217873a51fa518a97efbb963f992edb1823fb7c9845ce4381f3169728fea57937e9f1d4d3414eda11d66147462fe59634ba20def88afac6f9fbb4d97a4888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
